language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

before_deploy:
  - mkdir -p before-deploy/
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy 로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/book_spring-boot-aws.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repos에 설정
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-aws-build
    region: ap-northeast-2
    skip_cleanup: ture
    acl: private # zip 파일 접근 권한한
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repos에 설정
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-aws-build
    key: book_spring-boot-aws.zip
    bundle_type: zip
    application: spring-boot-aws-webapp
    deployment_group: spring-boot-aws-webapp
    region: ap-northeast-2
    wait_until_deployed: true

# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - gryb809@gmail.com